'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import jsQR from 'jsqr';
import { useToast } from '@/components/ToastProvider';
import { extractRoomCode } from '@/lib/urls';
import { BlurFade } from '@/components/magicui/BlurFade';
import { BorderBeam } from '@/components/magicui/BorderBeam';
import { trackProductEvent } from '@/lib/analytics';
import { decodeQrFromImageElement } from '@/lib/qr-decoder';

type ScanMode = 'camera' | 'upload';

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

export default function ScanPage() {
  const router = useRouter();
  const { toast } = useToast();

  const [scanMode, setScanMode] = useState<ScanMode>('camera');

  // Scanner States: 'initializing' | 'scanning' | 'detected' | 'error' | 'denied'
  const [scannerState, setScannerState] = useState<
    'initializing' | 'scanning' | 'detected' | 'error' | 'denied'
  >('initializing');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [inputVal, setInputVal] = useState<string>('');
  const [detectedCode, setDetectedCode] = useState<string | null>(null);
  const [isProcessingImage, setIsProcessingImage] = useState<boolean>(false);
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const [previewImageUrl, setPreviewImageUrl] = useState<string | null>(null);
  const [uploadedFileName, setUploadedFileName] = useState<string | null>(null);

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const animationFrameRef = useRef<number | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const hasProcessedRef = useRef<boolean>(false);
  const isCleaningUpRef = useRef<boolean>(false);
  const activePreviewUrlRef = useRef<string | null>(null);
  const processingTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const barcodeDetectorRef = useRef<any>(null);

  // Initialize native BarcodeDetector if supported
  useEffect(() => {
    if (typeof window !== 'undefined' && 'BarcodeDetector' in window) {
      try {
        barcodeDetectorRef.current = new (window as any).BarcodeDetector({ formats: ['qr_code'] });
      } catch {
        barcodeDetectorRef.current = null;
      }
    }
  }, []);

  // Clean up camera stream and video frame loops
  const stopCamera = useCallback(() => {
    isCleaningUpRef.current = true;
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = null;
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => {
        try {
          track.stop();
        } catch {}
      });
      streamRef.current = null;
    }
    if (videoRef.current) {
      try {
        videoRef.current.pause();
        videoRef.current.srcObject = null;
      } catch {}
    }
  }, []);

  // Clean up temporary image object URLs immediately
  const clearPreviewUrl = useCallback(() => {
    if (activePreviewUrlRef.current) {
      try {
        URL.revokeObjectURL(activePreviewUrlRef.current);
      } catch {}
      activePreviewUrlRef.current = null;
    }
    setPreviewImageUrl(null);
    setUploadedFileName(null);
  }, []);

  const clearProcessingTimeout = useCallback(() => {
    if (processingTimeoutRef.current) {
      clearTimeout(processingTimeoutRef.current);
      processingTimeoutRef.current = null;
    }
  }, []);

  // Shared single success & extraction pipeline
  const handleQrPayload = useCallback(
    (rawPayload: string) => {
      // Strict single-scan lock
      if (hasProcessedRef.current || isCleaningUpRef.current) {
        return;
      }

      clearProcessingTimeout();

      const roomCode = extractRoomCode(rawPayload);

      if (!roomCode) {
        setScannerState('error');
        setErrorMessage('Invalid TempLink QR. Please choose or scan a QR code generated by TempLink.');
        toast('Invalid TempLink QR code', 'error', 3500, 'qr-scan-error');
        setIsProcessingImage(false);
        return;
      }

      // Lock further detections for this session
      hasProcessedRef.current = true;
      setIsProcessingImage(false);

      // Stop camera hardware immediately
      stopCamera();

      // Track product event (strictly no sensitive payloads stored)
      trackProductEvent('qr_scan_success');

      setDetectedCode(roomCode);
      setScannerState('detected');

      // Navigate to /join with code populated (does NOT auto-join room)
      setTimeout(() => {
        clearPreviewUrl();
        router.push(`/join?code=${encodeURIComponent(roomCode)}&scanned=1`);
      }, 350);
    },
    [router, stopCamera, clearPreviewUrl, clearProcessingTimeout, toast]
  );

  const startScanningLoop = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;

    let offscreenCanvas = canvasRef.current;
    if (!offscreenCanvas) {
      offscreenCanvas = document.createElement('canvas');
      canvasRef.current = offscreenCanvas;
    }
    const ctx = offscreenCanvas.getContext('2d', { willReadFrequently: true });

    let isScanningFrame = false;

    const scanFrame = async () => {
      if (hasProcessedRef.current || isCleaningUpRef.current || scanMode !== 'camera') {
        return;
      }

      if (video.readyState === video.HAVE_ENOUGH_DATA && !isScanningFrame) {
        isScanningFrame = true;

        // Tier 1: Hardware-Accelerated Native BarcodeDetector on video element
        if (barcodeDetectorRef.current) {
          try {
            const barcodes = await barcodeDetectorRef.current.detect(video);
            if (barcodes && barcodes.length > 0 && barcodes[0].rawValue && !hasProcessedRef.current) {
              handleQrPayload(barcodes[0].rawValue);
              return;
            }
          } catch {}
        }

        // Tier 2: Downscaled Canvas + jsQR Fallback (Max 640px for 60fps performance)
        if (ctx && !hasProcessedRef.current) {
          const vw = video.videoWidth || 640;
          const vh = video.videoHeight || 480;
          const scale = Math.min(1, 640 / Math.max(vw, vh));
          const cw = Math.round(vw * scale);
          const ch = Math.round(vh * scale);

          offscreenCanvas!.width = cw;
          offscreenCanvas!.height = ch;
          ctx.drawImage(video, 0, 0, cw, ch);

          const imageData = ctx.getImageData(0, 0, cw, ch);
          const code = jsQR(imageData.data, cw, ch, {
            inversionAttempts: 'attemptBoth',
          });

          if (code && code.data && !hasProcessedRef.current) {
            handleQrPayload(code.data);
            return;
          }
        }

        isScanningFrame = false;
      }

      if (!hasProcessedRef.current && !isCleaningUpRef.current) {
        animationFrameRef.current = requestAnimationFrame(scanFrame);
      }
    };

    animationFrameRef.current = requestAnimationFrame(scanFrame);
  }, [handleQrPayload, scanMode]);

  const startCamera = useCallback(async () => {
    // Reset locks for a fresh scan session
    hasProcessedRef.current = false;
    isCleaningUpRef.current = false;
    clearPreviewUrl();
    clearProcessingTimeout();
    setScannerState('initializing');
    setErrorMessage(null);

    try {
      if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
        setScannerState('denied');
        setErrorMessage('Camera access is not supported by your browser.');
        return;
      }

      let stream: MediaStream;
      try {
        // Try rear/environment camera first
        stream = await navigator.mediaDevices.getUserMedia({
          video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } },
          audio: false,
        });
      } catch {
        // Fallback to any available camera
        stream = await navigator.mediaDevices.getUserMedia({
          video: true,
          audio: false,
        });
      }

      if (isCleaningUpRef.current || hasProcessedRef.current) {
        stream.getTracks().forEach((t) => t.stop());
        return;
      }

      streamRef.current = stream;

      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.setAttribute('playsinline', 'true');
        await videoRef.current.play();
        if (!hasProcessedRef.current && !isCleaningUpRef.current) {
          setScannerState('scanning');
          startScanningLoop();
        }
      }
    } catch (err: any) {
      if (isCleaningUpRef.current) return;
      setScannerState('denied');
      if (err.name === 'NotAllowedError' || err.name === 'PermissionDeniedError') {
        setErrorMessage('Camera permission was denied. You can choose a QR image from your gallery.');
      } else {
        setErrorMessage('Camera is unavailable or in use by another application.');
      }
    }
  }, [startScanningLoop, clearPreviewUrl, clearProcessingTimeout]);

  // Mode change lifecycle
  useEffect(() => {
    if (scanMode === 'camera') {
      startCamera();
    } else {
      stopCamera();
      setScannerState('scanning');
      setErrorMessage(null);
    }
    return () => {
      stopCamera();
      clearPreviewUrl();
      clearProcessingTimeout();
    };
  }, [scanMode, startCamera, stopCamera, clearPreviewUrl, clearProcessingTimeout]);

  // Local, privacy-first QR decoding from client file (Zero server uploads)
  const processQrImageFile = async (file: File) => {
    // 1. File type validation
    if (!file || !file.type.startsWith('image/')) {
      setScannerState('error');
      setErrorMessage('Unsupported file. Please choose a PNG, JPG, JPEG, or WEBP image.');
      toast('Please choose a valid image file', 'error');
      return;
    }

    // 2. File size validation (10 MB maximum)
    if (file.size > MAX_FILE_SIZE) {
      setScannerState('error');
      setErrorMessage('Image is too large. Choose an image smaller than 10 MB.');
      toast('Image is too large (maximum 10 MB)', 'error');
      return;
    }

    // Reset processing state
    hasProcessedRef.current = false;
    setIsProcessingImage(true);
    setErrorMessage(null);
    setUploadedFileName(file.name || 'image.png');
    clearProcessingTimeout();

    // Create temporary local object URL for preview
    clearPreviewUrl();
    const objectUrl = URL.createObjectURL(file);
    activePreviewUrlRef.current = objectUrl;
    setPreviewImageUrl(objectUrl);
    setUploadedFileName(file.name || 'image.png');

    // Strict safety timeout (4 seconds)
    processingTimeoutRef.current = setTimeout(() => {
      setIsProcessingImage(false);
      setScannerState('error');
      setErrorMessage('No QR code detected. Choose an image with a clearly visible TempLink QR code.');
    }, 4000);

    try {
      // Read file as Data URL for universal browser compatibility
      const dataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = () => reject(new Error('Failed to read image file'));
        reader.readAsDataURL(file);
      });

      const img = new Image();
      await new Promise<void>((resolve, reject) => {
        img.onload = () => resolve();
        img.onerror = () => reject(new Error('Failed to load image'));
        img.src = dataUrl;
      });

      // Small async yield to allow preview to paint
      await new Promise((r) => setTimeout(r, 40));

      const result = await decodeQrFromImageElement(img);

      clearProcessingTimeout();
      setIsProcessingImage(false);

      if (result.success && result.data) {
        handleQrPayload(result.data);
      } else {
        setScannerState('error');
        setErrorMessage('No TempLink QR code found in this image.');
        toast('No QR code found in image', 'error', 3500, 'qr-not-found');
      }
    } catch (err: any) {
      clearProcessingTimeout();
      setIsProcessingImage(false);
      setScannerState('error');
      setErrorMessage("We couldn't process this image. Please try another image.");
      toast('Unable to process image', 'error');
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processQrImageFile(file);
    }
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) {
      processQrImageFile(file);
    }
  };

  const handleManualSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputVal.trim()) return;

    const roomCode = extractRoomCode(inputVal);
    if (!roomCode) {
      toast('Please enter a valid room code or join URL', 'error', 3000, 'manual-error');
      return;
    }

    stopCamera();
    clearPreviewUrl();
    router.push(`/join?code=${encodeURIComponent(roomCode)}`);
  };

  const handleRetryScan = () => {
    clearProcessingTimeout();
    setIsProcessingImage(false);
    if (scanMode === 'camera') {
      stopCamera();
      startCamera();
    } else {
      setErrorMessage(null);
      setScannerState('scanning');
      clearPreviewUrl();
      fileInputRef.current?.click();
    }
  };

  const handleCancelProcessing = () => {
    clearProcessingTimeout();
    setIsProcessingImage(false);
    setScannerState('scanning');
    setErrorMessage(null);
    clearPreviewUrl();
  };

  return (
    <main className="flex-1 w-full max-w-container-max mx-auto px-4 md:px-lg py-8 sm:py-12 flex flex-col items-center justify-center min-h-[calc(100vh-80px)] min-h-[calc(100dvh-80px)] relative z-10 bg-[#05070B] text-slate-100 pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]">
      <BlurFade delay={0.1} className="w-full max-w-[500px]">
        <header className="mb-5 sm:mb-6 text-center">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#0D111A] border border-white/10 text-primary-light text-xs font-semibold mb-2">
            <span className="material-symbols-outlined text-[15px]">qr_code_scanner</span>
            Visual Room Code Scanner
          </div>
          <h1 className="font-display text-2xl sm:text-3xl font-bold text-white mb-1">
            Scan Room QR Code
          </h1>
          <p className="text-xs sm:text-sm text-slate-400">
            Scan with your device camera or upload a saved QR image.
          </p>
        </header>

        {/* Hidden file input for native mobile / system file picker */}
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          className="hidden"
          onChange={handleFileChange}
        />

        <div className="relative glass-panel p-5 sm:p-8 rounded-3xl flex flex-col items-center gap-5 sm:gap-6 border border-white/10 bg-[#080B12]/90 shadow-2xl overflow-hidden">
          {/* Border Beam Accent */}
          <BorderBeam size={200} duration={8} colorFrom="#6366F1" colorTo="#38BDF8" />

          {/* Mode Switcher Tabs */}
          <div className="grid grid-cols-2 p-1 bg-[#0D111A] rounded-2xl border border-white/10 w-full max-w-[340px]">
            <button
              type="button"
              onClick={() => {
                setScanMode('camera');
                setErrorMessage(null);
                clearPreviewUrl();
              }}
              className={`min-h-[44px] py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-1.5 focus:outline-none focus:ring-2 focus:ring-primary ${
                scanMode === 'camera'
                  ? 'bg-primary text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <span className="material-symbols-outlined text-[18px]">videocam</span>
              <span>Scan with Camera</span>
            </button>
            <button
              type="button"
              onClick={() => {
                setScanMode('upload');
                setErrorMessage(null);
              }}
              className={`min-h-[44px] py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-1.5 focus:outline-none focus:ring-2 focus:ring-primary ${
                scanMode === 'upload'
                  ? 'bg-primary text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <span className="material-symbols-outlined text-[18px]">photo_library</span>
              <span>Upload from Gallery</span>
            </button>
          </div>

          {/* MAIN SCANNER AREA */}
          {scanMode === 'camera' ? (
            /* CAMERA VIEWPORT */
            <div className="relative w-full aspect-square max-w-[320px] bg-black rounded-2xl overflow-hidden border border-white/15 flex items-center justify-center shadow-inner">
              <video
                ref={videoRef}
                playsInline
                muted
                className={`w-full h-full object-cover transition-opacity duration-300 ${
                  scannerState === 'scanning' ? 'opacity-100' : 'opacity-30'
                }`}
              />

              {/* Target Reticle Overlay */}
              {scannerState === 'scanning' && (
                <div className="absolute inset-8 border-2 border-primary/60 rounded-2xl pointer-events-none flex items-center justify-center">
                  <div className="w-full h-0.5 bg-primary shadow-[0_0_8px_#6366F1] animate-pulse" />
                  <div className="absolute top-0 left-0 w-5 h-5 border-t-2 border-l-2 border-primary-light rounded-tl-lg" />
                  <div className="absolute top-0 right-0 w-5 h-5 border-t-2 border-r-2 border-primary-light rounded-tr-lg" />
                  <div className="absolute bottom-0 left-0 w-5 h-5 border-b-2 border-l-2 border-primary-light rounded-bl-lg" />
                  <div className="absolute bottom-0 right-0 w-5 h-5 border-b-2 border-r-2 border-primary-light rounded-br-lg" />
                </div>
              )}

              {/* State Overlays */}
              {scannerState === 'initializing' && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-black/70 p-6 text-center">
                  <div className="w-8 h-8 rounded-full border-2 border-primary border-t-transparent animate-spin motion-reduce:animate-none" />
                  <span className="text-xs font-semibold text-white">Initializing camera...</span>
                </div>
              )}

              {scannerState === 'detected' && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-black/85 p-6 text-center animate-fade-in">
                  <span className="material-symbols-outlined text-4xl text-emerald-400 animate-bounce motion-reduce:animate-none">
                    check_circle
                  </span>
                  <span className="text-sm font-bold text-white">QR Code Detected!</span>
                  <span className="text-xs text-primary-light font-mono font-bold">
                    {detectedCode}
                  </span>
                  <span className="text-[11px] text-slate-400">Auto-filling room code...</span>
                </div>
              )}

              {(scannerState === 'denied' || (scannerState === 'error' && !previewImageUrl)) && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-[#080B12]/95 p-6 text-center animate-fade-in">
                  <span className="material-symbols-outlined text-4xl text-amber-400">
                    {scannerState === 'denied' ? 'videocam_off' : 'error'}
                  </span>
                  <span className="text-xs font-semibold text-white max-w-[220px]">
                    {errorMessage || 'Unable to scan QR code.'}
                  </span>
                  <div className="flex items-center gap-2 mt-2">
                    <button
                      onClick={handleRetryScan}
                      className="btn-ghost text-xs font-semibold px-3 py-2 rounded-xl flex items-center gap-1 min-h-[40px]"
                    >
                      <span className="material-symbols-outlined text-[15px]">refresh</span>
                      Try Again
                    </button>
                    <button
                      onClick={() => {
                        setScanMode('upload');
                        setErrorMessage(null);
                      }}
                      className="btn-primary text-xs font-bold px-3 py-2 rounded-xl uppercase tracking-wider min-h-[40px]"
                    >
                      Upload Image
                    </button>
                  </div>
                </div>
              )}
            </div>
          ) : (
            /* UPLOAD FROM GALLERY VIEWPORT (Enhanced Responsive & State-Aware) */
            <div
              onDragOver={(e) => {
                e.preventDefault();
                setIsDragging(true);
              }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={handleDrop}
              onClick={() => {
                if (!isProcessingImage) {
                  fileInputRef.current?.click();
                }
              }}
              className={`relative w-full aspect-square max-w-[320px] rounded-2xl border-2 border-dashed transition-all flex flex-col items-center justify-center p-6 text-center cursor-pointer overflow-hidden shadow-inner ${
                isDragging
                  ? 'border-primary bg-primary/15 scale-[0.99] shadow-[0_0_25px_rgba(99,102,241,0.3)]'
                  : previewImageUrl && scannerState === 'error'
                  ? 'border-amber-500/40 bg-[#0B0D14]'
                  : 'border-white/20 bg-[#05070B] hover:border-primary/50 hover:bg-[#0D111A]'
              }`}
            >
              {/* Optional Local Image Preview */}
              {previewImageUrl && (
                <img
                  src={previewImageUrl}
                  alt="Selected QR preview"
                  className={`absolute inset-0 w-full h-full object-contain ${
                    isProcessingImage ? 'opacity-40 filter blur-[1px]' : 'opacity-25'
                  }`}
                />
              )}

              {/* State A: Scanning Active */}
              {isProcessingImage ? (
                <div className="relative z-10 flex flex-col items-center gap-3 bg-black/85 p-5 rounded-2xl backdrop-blur-md shadow-xl border border-white/10">
                  <div className="w-9 h-9 rounded-full border-2 border-primary border-t-transparent animate-spin motion-reduce:animate-none" />
                  <span className="text-xs font-bold text-white">Scanning image...</span>
                  <span className="text-[11px] text-slate-300">Processing locally in your browser</span>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleCancelProcessing();
                    }}
                    className="mt-1 text-[11px] text-slate-400 hover:text-white underline"
                  >
                    Cancel
                  </button>
                </div>
              ) : scannerState === 'detected' ? (
                /* State B: QR Code Successfully Detected */
                <div className="relative z-10 flex flex-col items-center gap-3 bg-black/85 p-5 rounded-2xl backdrop-blur-md animate-fade-in border border-emerald-500/30">
                  <span className="material-symbols-outlined text-4xl text-emerald-400 animate-bounce motion-reduce:animate-none">
                    check_circle
                  </span>
                  <span className="text-sm font-bold text-white">QR Code Detected!</span>
                  <span className="text-xs text-primary-light font-mono font-bold">
                    {detectedCode}
                  </span>
                  <span className="text-[11px] text-slate-300">Auto-filling room code...</span>
                </div>
              ) : previewImageUrl && scannerState === 'error' ? (
                /* State C: Image Uploaded but No QR Detected */
                <div className="relative z-10 flex flex-col items-center gap-2.5 w-full bg-black/80 p-4 rounded-2xl backdrop-blur-md border border-amber-500/20">
                  <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400 shadow-sm">
                    <span className="material-symbols-outlined text-[22px]">qr_code_2</span>
                  </div>
                  <div>
                    <span className="text-xs font-bold text-white block">
                      Image Received
                    </span>
                    <span className="text-[11px] text-amber-300/90 block mt-0.5 max-w-[220px]">
                      {errorMessage || 'No TempLink QR code found in this image.'}
                    </span>
                    {uploadedFileName && (
                      <span className="text-[10px] text-slate-400 block font-mono mt-1 truncate max-w-[200px]">
                        {uploadedFileName}
                      </span>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      fileInputRef.current?.click();
                    }}
                    className="btn-primary min-h-[40px] py-2 px-4 rounded-xl text-xs font-bold uppercase tracking-wider mt-1 shadow-md w-full max-w-[190px]"
                  >
                    Choose Another Image
                  </button>
                </div>
              ) : (
                /* State D: Default Initial Upload Dropzone */
                <div className="relative z-10 flex flex-col items-center gap-3 w-full">
                  <div className="w-14 h-14 rounded-2xl bg-[#101621] border border-white/10 flex items-center justify-center text-primary-light shadow-sm">
                    <span className="material-symbols-outlined text-[28px]">
                      {isDragging ? 'download' : 'add_photo_alternate'}
                    </span>
                  </div>
                  <div>
                    <span className="text-xs font-bold text-white block mb-1">
                      {isDragging ? 'Drop to scan QR' : 'Upload from Gallery'}
                    </span>
                    <span className="text-[11px] text-slate-400 block hidden md:inline">
                      Drag &amp; drop an image here or click to browse
                    </span>
                    <span className="text-[11px] text-slate-400 block md:hidden">
                      Choose an image containing a TempLink QR code
                    </span>
                    <span className="text-[10px] text-slate-500 block mt-1 font-mono">
                      PNG • JPG • WEBP • up to 10 MB
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      fileInputRef.current?.click();
                    }}
                    className="btn-primary min-h-[44px] py-2.5 px-5 rounded-xl text-xs font-bold uppercase tracking-wider mt-1 shadow-md w-full max-w-[200px]"
                  >
                    Choose Image
                  </button>
                  <span className="text-[10px] text-slate-500 block">
                    Screenshots and saved QR images are supported
                  </span>
                </div>
              )}
            </div>
          )}

          {/* Additional Error Feedback / Action helper */}
          {errorMessage && !previewImageUrl && (
            <div className="p-3.5 bg-red-950/40 border border-red-500/30 rounded-xl text-xs text-red-200 text-center w-full max-w-[320px] flex flex-col gap-2 animate-fade-in">
              <span className="font-semibold">{errorMessage}</span>
              {scanMode === 'upload' && (
                <div className="flex gap-2 justify-center mt-1">
                  <button
                    type="button"
                    onClick={() => fileInputRef.current?.click()}
                    className="btn-primary text-[10px] font-bold py-1.5 px-3 rounded-lg uppercase min-h-[36px]"
                  >
                    Choose Another Image
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setScanMode('camera');
                      setErrorMessage(null);
                    }}
                    className="btn-ghost text-[10px] font-semibold py-1.5 px-3 rounded-lg min-h-[36px]"
                  >
                    Scan with Camera
                  </button>
                </div>
              )}
            </div>
          )}

          {/* Privacy Hint */}
          <div className="text-center text-[11px] text-slate-400 max-w-[300px]">
            {scanMode === 'camera' && scannerState === 'scanning' && (
              <span className="flex items-center justify-center gap-1.5 text-emerald-400 font-medium">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                Live Camera Active — Align QR code within frame
              </span>
            )}
            {scanMode === 'upload' && !isProcessingImage && (
              <span className="text-slate-400 flex items-center justify-center gap-1 text-[11px]">
                <span className="material-symbols-outlined text-[14px] text-primary-light">lock</span>
                Your image is processed on this device and is not uploaded to TempLink.
              </span>
            )}
          </div>

          {/* Manual Input Fallback */}
          <form onSubmit={handleManualSubmit} className="w-full flex flex-col gap-2">
            <label className="text-[10px] uppercase font-semibold text-slate-500 tracking-wider text-center">
              Or paste join link / enter code manually
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                placeholder="e.g. K7XM-4P2Q or join URL"
                value={inputVal}
                onChange={(e) => setInputVal(e.target.value)}
                className="flex-1 bg-[#05070B] border border-white/15 rounded-xl px-4 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-primary font-mono tracking-wider min-h-[44px]"
              />
              <button
                type="submit"
                disabled={!inputVal.trim()}
                className="btn-primary px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider disabled:opacity-50 shadow-sm min-h-[44px]"
              >
                Use Code
              </button>
            </div>
          </form>

          <Link
            href="/join"
            className="text-xs text-slate-400 hover:text-primary-light transition-colors flex items-center gap-1 font-semibold min-h-[40px]"
          >
            <span className="material-symbols-outlined text-[15px]">arrow_back</span>
            Back to Manual Code Entry
          </Link>
        </div>
      </BlurFade>
    </main>
  );
}
