'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import jsQR from 'jsqr';
import { useToast } from '@/components/ToastProvider';
import { extractRoomCode } from '@/lib/urls';
import { BlurFade } from '@/components/magicui/BlurFade';
import { BorderBeam } from '@/components/magicui/BorderBeam';
import { trackProductEvent } from '@/lib/analytics';

type ScanMode = 'camera' | 'upload';

export default function ScanPage() {
  const router = useRouter();
  const { toast } = useToast();

  const [scanMode, setScanMode] = useState<ScanMode>('camera');

  // Scanner States: 'initializing' | 'scanning' | 'detected' | 'error' | 'denied'
  const [scannerState, setScannerState] = useState<
    'initializing' | 'scanning' | 'detected' | 'error' | 'denied'
  >('initializing');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [inputVal, setInputVal] = useState<string>('');
  const [detectedCode, setDetectedCode] = useState<string | null>(null);
  const [isProcessingImage, setIsProcessingImage] = useState<boolean>(false);
  const [isDragging, setIsDragging] = useState<boolean>(false);

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const animationFrameRef = useRef<number | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const hasProcessedRef = useRef<boolean>(false);
  const isCleaningUpRef = useRef<boolean>(false);

  const stopCamera = useCallback(() => {
    isCleaningUpRef.current = true;
    if (animationFrameRef.current) {
      cancelAnimationFrame(animationFrameRef.current);
      animationFrameRef.current = null;
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => {
        try {
          track.stop();
        } catch {}
      });
      streamRef.current = null;
    }
    if (videoRef.current) {
      try {
        videoRef.current.pause();
        videoRef.current.srcObject = null;
      } catch {}
    }
  }, []);

  const handleValidRoomCode = useCallback(
    (rawPayload: string) => {
      // Strict single-scan lock
      if (hasProcessedRef.current || isCleaningUpRef.current) {
        return;
      }

      const roomCode = extractRoomCode(rawPayload);

      if (!roomCode) {
        setScannerState('error');
        setErrorMessage('Invalid TempLink QR code. Please scan or upload a QR code generated by TempLink.');
        toast('Invalid TempLink QR code', 'error', 3000, 'qr-scan-error');
        setIsProcessingImage(false);
        return;
      }

      // Lock further detections
      hasProcessedRef.current = true;
      setIsProcessingImage(false);

      // Stop camera hardware and frame decoding immediately
      stopCamera();

      // Track QR scan milestone (without sensitive payloads)
      trackProductEvent('qr_scan_success');

      setDetectedCode(roomCode);
      setScannerState('detected');

      // Navigate to /join with scanned code (fills input, does not auto-join)
      setTimeout(() => {
        router.push(`/join?code=${encodeURIComponent(roomCode)}&scanned=1`);
      }, 400);
    },
    [router, stopCamera, toast]
  );

  const startScanningLoop = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;

    let offscreenCanvas = canvasRef.current;
    if (!offscreenCanvas) {
      offscreenCanvas = document.createElement('canvas');
      canvasRef.current = offscreenCanvas;
    }
    const ctx = offscreenCanvas.getContext('2d', { willReadFrequently: true });

    const scanFrame = () => {
      if (hasProcessedRef.current || isCleaningUpRef.current || scanMode !== 'camera') {
        return;
      }

      if (video.readyState === video.HAVE_ENOUGH_DATA && ctx) {
        offscreenCanvas!.width = video.videoWidth;
        offscreenCanvas!.height = video.videoHeight;
        ctx.drawImage(video, 0, 0, offscreenCanvas!.width, offscreenCanvas!.height);

        const imageData = ctx.getImageData(0, 0, offscreenCanvas!.width, offscreenCanvas!.height);
        const code = jsQR(imageData.data, imageData.width, imageData.height, {
          inversionAttempts: 'dontInvert',
        });

        if (code && code.data && !hasProcessedRef.current) {
          handleValidRoomCode(code.data);
          return;
        }
      }

      if (!hasProcessedRef.current && !isCleaningUpRef.current) {
        animationFrameRef.current = requestAnimationFrame(scanFrame);
      }
    };

    animationFrameRef.current = requestAnimationFrame(scanFrame);
  }, [handleValidRoomCode, scanMode]);

  const startCamera = useCallback(async () => {
    // Reset locks for a fresh scan session
    hasProcessedRef.current = false;
    isCleaningUpRef.current = false;
    setScannerState('initializing');
    setErrorMessage(null);

    try {
      if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
        setScannerState('denied');
        setErrorMessage('Camera access is not supported by your browser.');
        return;
      }

      let stream: MediaStream;
      try {
        // Try rear/environment camera first
        stream = await navigator.mediaDevices.getUserMedia({
          video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } },
          audio: false,
        });
      } catch {
        // Fallback to any available camera
        stream = await navigator.mediaDevices.getUserMedia({
          video: true,
          audio: false,
        });
      }

      if (isCleaningUpRef.current || hasProcessedRef.current) {
        stream.getTracks().forEach((t) => t.stop());
        return;
      }

      streamRef.current = stream;

      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.setAttribute('playsinline', 'true');
        await videoRef.current.play();
        if (!hasProcessedRef.current && !isCleaningUpRef.current) {
          setScannerState('scanning');
          startScanningLoop();
        }
      }
    } catch (err: any) {
      if (isCleaningUpRef.current) return;
      setScannerState('denied');
      if (err.name === 'NotAllowedError' || err.name === 'PermissionDeniedError') {
        setErrorMessage('Camera permission was denied. You can upload a QR image or enter the code manually.');
      } else {
        setErrorMessage('Camera is unavailable or in use by another app.');
      }
    }
  }, [startScanningLoop]);

  // Mode change handler
  useEffect(() => {
    if (scanMode === 'camera') {
      startCamera();
    } else {
      stopCamera();
      setScannerState('scanning');
      setErrorMessage(null);
    }
    return () => {
      stopCamera();
    };
  }, [scanMode, startCamera, stopCamera]);

  // Client-side QR decoding from an uploaded image File
  const processQrImageFile = (file: File) => {
    if (!file.type.startsWith('image/')) {
      toast('Please upload a valid image file (PNG, JPG, WebP)', 'error');
      return;
    }

    setIsProcessingImage(true);
    setErrorMessage(null);

    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result;
      if (typeof result !== 'string') {
        setIsProcessingImage(false);
        toast('Failed to read image file', 'error');
        return;
      }

      const img = new Image();
      img.onload = () => {
        // Create in-memory canvas for decoding
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d', { willReadFrequently: true });
        if (!ctx) {
          setIsProcessingImage(false);
          toast('Failed to initialize image decoder', 'error');
          return;
        }

        // Scale image proportionally for optimal decoding performance
        const maxDimension = 1400;
        let width = img.width;
        let height = img.height;

        if (width > maxDimension || height > maxDimension) {
          if (width > height) {
            height = Math.round((height * maxDimension) / width);
            width = maxDimension;
          } else {
            width = Math.round((width * maxDimension) / height);
            height = maxDimension;
          }
        }

        canvas.width = width;
        canvas.height = height;
        ctx.drawImage(img, 0, 0, width, height);

        const imageData = ctx.getImageData(0, 0, width, height);
        // Attempt detection with both normal and inverted polarities
        let code = jsQR(imageData.data, imageData.width, imageData.height, {
          inversionAttempts: 'attemptBoth',
        });

        // Fallback: If not found, try analyzing at original native resolution
        if (!code && (img.width !== width || img.height !== height)) {
          canvas.width = img.width;
          canvas.height = img.height;
          ctx.drawImage(img, 0, 0, img.width, img.height);
          const nativeData = ctx.getImageData(0, 0, img.width, img.height);
          code = jsQR(nativeData.data, nativeData.width, nativeData.height, {
            inversionAttempts: 'attemptBoth',
          });
        }

        if (code && code.data) {
          handleValidRoomCode(code.data);
        } else {
          setIsProcessingImage(false);
          setErrorMessage('No valid TempLink QR code found in the selected image. Please try another image.');
          toast('No TempLink QR code found in image', 'error', 3500, 'qr-not-found');
        }
      };

      img.onerror = () => {
        setIsProcessingImage(false);
        toast('Unable to process the selected image', 'error');
      };

      img.src = result;
    };

    reader.onerror = () => {
      setIsProcessingImage(false);
      toast('Failed to load image file', 'error');
    };

    reader.readAsDataURL(file);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processQrImageFile(file);
    }
    // Reset file input so same file can be re-selected if needed
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) {
      processQrImageFile(file);
    }
  };

  const handleManualSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputVal.trim()) return;

    const roomCode = extractRoomCode(inputVal);
    if (!roomCode) {
      toast('Please enter a valid room code or join URL', 'error', 3000, 'manual-error');
      return;
    }

    stopCamera();
    router.push(`/join?code=${encodeURIComponent(roomCode)}`);
  };

  const handleRetryScan = () => {
    stopCamera();
    startCamera();
  };

  return (
    <main className="flex-1 w-full max-w-container-max mx-auto px-4 md:px-lg py-12 flex flex-col items-center justify-center min-h-[calc(100vh-80px)] min-h-[calc(100dvh-80px)] relative z-10 bg-[#05070B] text-slate-100">
      <BlurFade delay={0.1} className="w-full max-w-[500px] mt-2">
        <header className="mb-6 text-center">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#0D111A] border border-white/10 text-primary-light text-xs font-semibold mb-2">
            <span className="material-symbols-outlined text-[15px]">qr_code_scanner</span>
            Visual Room Code Scanner
          </div>
          <h1 className="font-display text-2xl sm:text-3xl font-bold text-white mb-1">
            Scan Room QR Code
          </h1>
          <p className="text-xs sm:text-sm text-slate-400">
            Scan with your device camera or upload a QR image from your gallery.
          </p>
        </header>

        {/* Hidden file input for gallery upload */}
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          className="hidden"
          onChange={handleFileChange}
        />

        <div className="relative glass-panel p-6 sm:p-8 rounded-3xl flex flex-col items-center gap-6 border border-white/10 bg-[#080B12]/90 shadow-2xl overflow-hidden">
          {/* Border Beam Accent */}
          <BorderBeam size={200} duration={8} colorFrom="#6366F1" colorTo="#38BDF8" />

          {/* Mode Switcher Tabs */}
          <div className="grid grid-cols-2 p-1 bg-[#0D111A] rounded-2xl border border-white/10 w-full max-w-[320px]">
            <button
              type="button"
              onClick={() => {
                setScanMode('camera');
                setErrorMessage(null);
              }}
              className={`py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-1.5 ${
                scanMode === 'camera'
                  ? 'bg-primary text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <span className="material-symbols-outlined text-[16px]">videocam</span>
              <span>Scan with Camera</span>
            </button>
            <button
              type="button"
              onClick={() => {
                setScanMode('upload');
                setErrorMessage(null);
              }}
              className={`py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-1.5 ${
                scanMode === 'upload'
                  ? 'bg-primary text-white shadow-md'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              <span className="material-symbols-outlined text-[16px]">photo_library</span>
              <span>Upload from Gallery</span>
            </button>
          </div>

          {/* MAIN SCANNER AREA */}
          {scanMode === 'camera' ? (
            /* CAMERA VIEWPORT */
            <div className="relative w-full aspect-square max-w-[320px] bg-black rounded-2xl overflow-hidden border border-white/15 flex items-center justify-center shadow-inner">
              <video
                ref={videoRef}
                playsInline
                muted
                className={`w-full h-full object-cover transition-opacity duration-300 ${
                  scannerState === 'scanning' ? 'opacity-100' : 'opacity-30'
                }`}
              />

              {/* Target Reticle Overlay */}
              {scannerState === 'scanning' && (
                <div className="absolute inset-8 border-2 border-primary/60 rounded-2xl pointer-events-none flex items-center justify-center">
                  <div className="w-full h-0.5 bg-primary shadow-[0_0_8px_#6366F1] animate-pulse" />
                  <div className="absolute top-0 left-0 w-5 h-5 border-t-2 border-l-2 border-primary-light rounded-tl-lg" />
                  <div className="absolute top-0 right-0 w-5 h-5 border-t-2 border-r-2 border-primary-light rounded-tr-lg" />
                  <div className="absolute bottom-0 left-0 w-5 h-5 border-b-2 border-l-2 border-primary-light rounded-bl-lg" />
                  <div className="absolute bottom-0 right-0 w-5 h-5 border-b-2 border-r-2 border-primary-light rounded-br-lg" />
                </div>
              )}

              {/* State Overlays */}
              {scannerState === 'initializing' && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-black/70 p-6 text-center">
                  <div className="w-8 h-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                  <span className="text-xs font-semibold text-white">Initializing camera...</span>
                </div>
              )}

              {scannerState === 'detected' && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-black/85 p-6 text-center animate-fade-in">
                  <span className="material-symbols-outlined text-4xl text-emerald-400 animate-bounce">
                    check_circle
                  </span>
                  <span className="text-sm font-bold text-white">QR Code Detected!</span>
                  <span className="text-xs text-primary-light font-mono font-bold">
                    {detectedCode}
                  </span>
                  <span className="text-[11px] text-slate-400">Filling room code input...</span>
                </div>
              )}

              {(scannerState === 'denied' || scannerState === 'error') && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-[#080B12]/95 p-6 text-center animate-fade-in">
                  <span className="material-symbols-outlined text-4xl text-amber-400">
                    {scannerState === 'denied' ? 'videocam_off' : 'error'}
                  </span>
                  <span className="text-xs font-semibold text-white max-w-[220px]">
                    {errorMessage || 'Unable to scan QR code.'}
                  </span>
                  <div className="flex items-center gap-2 mt-2">
                    <button
                      onClick={handleRetryScan}
                      className="btn-ghost text-xs font-semibold px-3 py-2 rounded-xl flex items-center gap-1"
                    >
                      <span className="material-symbols-outlined text-[15px]">refresh</span>
                      Try Again
                    </button>
                    <button
                      onClick={() => {
                        setScanMode('upload');
                        setErrorMessage(null);
                      }}
                      className="btn-primary text-xs font-bold px-3 py-2 rounded-xl uppercase tracking-wider"
                    >
                      Upload Image
                    </button>
                  </div>
                </div>
              )}
            </div>
          ) : (
            /* UPLOAD FROM GALLERY VIEWPORT */
            <div
              onDragOver={(e) => {
                e.preventDefault();
                setIsDragging(true);
              }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
              className={`relative w-full aspect-square max-w-[320px] rounded-2xl border-2 border-dashed transition-all flex flex-col items-center justify-center p-6 text-center cursor-pointer shadow-inner ${
                isDragging
                  ? 'border-primary bg-primary/10 scale-[0.99]'
                  : 'border-white/20 bg-[#05070B] hover:border-primary/50 hover:bg-[#0D111A]'
              }`}
            >
              {isProcessingImage ? (
                <div className="flex flex-col items-center gap-3">
                  <div className="w-9 h-9 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                  <span className="text-xs font-bold text-white">Analyzing QR code...</span>
                  <span className="text-[11px] text-slate-400">Processing locally on device</span>
                </div>
              ) : scannerState === 'detected' ? (
                <div className="flex flex-col items-center gap-3 animate-fade-in">
                  <span className="material-symbols-outlined text-4xl text-emerald-400 animate-bounce">
                    check_circle
                  </span>
                  <span className="text-sm font-bold text-white">QR Code Found!</span>
                  <span className="text-xs text-primary-light font-mono font-bold">
                    {detectedCode}
                  </span>
                  <span className="text-[11px] text-slate-400">Filling room code input...</span>
                </div>
              ) : (
                <div className="flex flex-col items-center gap-3">
                  <div className="w-14 h-14 rounded-2xl bg-[#101621] border border-white/10 flex items-center justify-center text-primary-light shadow-sm">
                    <span className="material-symbols-outlined text-[28px]">add_photo_alternate</span>
                  </div>
                  <div>
                    <span className="text-xs font-bold text-white block mb-1">
                      Choose QR image from gallery
                    </span>
                    <span className="text-[11px] text-slate-400 block">
                      or drag &amp; drop an image here
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      fileInputRef.current?.click();
                    }}
                    className="btn-primary py-2 px-4 rounded-xl text-xs font-bold uppercase tracking-wider mt-1 shadow-md"
                  >
                    Select Photo
                  </button>
                </div>
              )}
            </div>
          )}

          {/* Scanner Status or Error Feedback */}
          {errorMessage && scanMode === 'upload' && (
            <div className="p-3 bg-red-950/40 border border-red-500/30 rounded-xl text-xs text-red-200 text-center w-full max-w-[320px]">
              {errorMessage}
            </div>
          )}

          <div className="text-center text-xs text-slate-400">
            {scanMode === 'camera' && scannerState === 'scanning' && (
              <span className="flex items-center justify-center gap-1.5 text-emerald-400 font-medium">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                Live Camera Active — Align QR code within frame
              </span>
            )}
            {scanMode === 'upload' && !isProcessingImage && (
              <span className="text-slate-400">
                Images are decoded entirely inside your browser (never uploaded).
              </span>
            )}
          </div>

          {/* Manual Input Fallback */}
          <form onSubmit={handleManualSubmit} className="w-full flex flex-col gap-2">
            <label className="text-[10px] uppercase font-semibold text-slate-500 tracking-wider text-center">
              Or paste join link / enter code manually
            </label>
            <div className="flex items-center gap-2">
              <input
                type="text"
                placeholder="e.g. K7XM-4P2Q or join URL"
                value={inputVal}
                onChange={(e) => setInputVal(e.target.value)}
                className="flex-1 bg-[#05070B] border border-white/15 rounded-xl px-4 py-2.5 text-xs text-white placeholder:text-slate-600 focus:outline-none focus:border-primary font-mono tracking-wider"
              />
              <button
                type="submit"
                disabled={!inputVal.trim()}
                className="btn-primary px-4 py-2.5 rounded-xl text-xs font-bold uppercase tracking-wider disabled:opacity-50 shadow-sm"
              >
                Use Code
              </button>
            </div>
          </form>

          <Link
            href="/join"
            className="text-xs text-slate-400 hover:text-primary-light transition-colors flex items-center gap-1 font-semibold"
          >
            <span className="material-symbols-outlined text-[15px]">arrow_back</span>
            Back to Manual Code Entry
          </Link>
        </div>
      </BlurFade>
    </main>
  );
}
